# This is a basic workflow to help you get started with Actions

name: Update file

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Download file with curl
        run: curl -o /tmp/downloaded_content.txt https://iptv-org.github.io/iptv/countries/in.m3u

      # Runs a set of commands using the runners shell
      - name: Copy from sample file
        run: |
          cat start.txt > /tmp/updated_file.txt
          tail -n +2 /tmp/downloaded_content.txt >> /tmp/updated_file.txt
          mv /tmp/updated_file.txt index.m3u
      - name: Commit changes
        run: |
          git config --global user.name "gitaction"
          git add index.m3u
          git commit -m "Updated file with downloaded content"
          git push
      - name: Purge jsDelivr cache
        uses: gacts/purge-jsdelivr-cache@v1.1.1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/tv-ip/t@main/index.m3u
            https://cdn.jsdelivr.net/gh/tv-ip/t@master/index.m3u
            
